### PR TITLE
see when your branch is ahead of upstream

### PR DESCRIPTION
**Pull request by applewiskey**

### CODE REVIEW

**Comment by pablopunk** [comment]
Hi! Thanks for the PR. I'd like to make a couple of changes to it:

```diff
-symbol_ahead="\x01\033[33m\x02>" # yellow
+symbol_ahead="\x01\033[33m\x02↑" # yellow
 
-echo -en "$bold$branch $symbols$normal"
+echo -en "$bold$repo$normal at $bold$branch $symbols$normal"
```

1. I prefer the symbol `↑`
2. Not sure why you removed the repo output, but I'd like to keep it

**Comment by applewiskey** [comment]
1. Sure.
2. Sorry, my mistake. It's a change that I have done for myself.

**Comment by pablopunk** [comment]
@applewiskey no problem! just make those changes and I'll merge it 👍🏻

**Comment by pablopunk** [comment]
Thanks!

**Comment by pablopunk** [comment]
https://github.com/pablopunk/bashy/releases/tag/2.6.0

```sh
npm i -g bashy@2.6.0
```

**Pull request merged**
